[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."sellasist-orders"]
  timeout = 26

[functions."sellasist-test"]
  timeout = 26

[dev]
  command = "npm run gatsby:dev"
  targetPort = 8000
  port = 8888
